import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/software/comsol/model-tree.html.vue"
const data = JSON.parse("{\"path\":\"/software/comsol/model-tree.html\",\"title\":\"模型树\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"模型树\",\"icon\":\"tree\",\"date\":\"2020-06-01T00:00:00.000Z\",\"category\":\"软件\",\"tag\":[\"仿真\",\"COMSOL\"],\"description\":\"使用“模型开发器”时，可通过以在默认的模型树中添加节点并编辑节点设置来构建模型。 默认模型树中的所有节点均为顶层父节点。可以右键单击这些节点以查看可在其中添加的子节点的列表。这是将节点添加到模型树的方式。 当您单击某个子节点时，可以在设置窗口中查看其节点设置。您可以在此编辑节点设置。\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/software/comsol/model-tree.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"模型树\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"使用“模型开发器”时，可通过以在默认的模型树中添加节点并编辑节点设置来构建模型。 默认模型树中的所有节点均为顶层父节点。可以右键单击这些节点以查看可在其中添加的子节点的列表。这是将节点添加到模型树的方式。 当您单击某个子节点时，可以在设置窗口中查看其节点设置。您可以在此编辑节点设置。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"仿真\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"COMSOL\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-06-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"模型树\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-06-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"根节点\",\"slug\":\"根节点\",\"link\":\"#根节点\",\"children\":[]},{\"level\":2,\"title\":\"全局定义\",\"slug\":\"全局定义\",\"link\":\"#全局定义\",\"children\":[]},{\"level\":2,\"title\":\"组件和研究节点\",\"slug\":\"组件和研究节点\",\"link\":\"#组件和研究节点\",\"children\":[]},{\"level\":2,\"title\":\"结果节点\",\"slug\":\"结果节点\",\"link\":\"#结果节点\",\"children\":[]},{\"level\":2,\"title\":\"参数、函数、变量和范围\",\"slug\":\"参数、函数、变量和范围\",\"link\":\"#参数、函数、变量和范围\",\"children\":[{\"level\":3,\"title\":\"全局参数\",\"slug\":\"全局参数\",\"link\":\"#全局参数\",\"children\":[]},{\"level\":3,\"title\":\"结果参数\",\"slug\":\"结果参数\",\"link\":\"#结果参数\",\"children\":[]},{\"level\":3,\"title\":\"函数\",\"slug\":\"函数\",\"link\":\"#函数\",\"children\":[]},{\"level\":3,\"title\":\"变量\",\"slug\":\"变量\",\"link\":\"#变量\",\"children\":[]},{\"level\":3,\"title\":\"App 中使用的变量\",\"slug\":\"app-中使用的变量\",\"link\":\"#app-中使用的变量\",\"children\":[]},{\"level\":3,\"title\":\"范围\",\"slug\":\"范围\",\"link\":\"#范围\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.19,\"words\":1858},\"filePathRelative\":\"software/comsol/model-tree.md\",\"localizedDate\":\"2020年6月1日\",\"excerpt\":\"<p>使用“模型开发器”时，可通过以在默认的模型树中添加节点并编辑节点设置来构建模型。</p>\\n<p>默认模型树中的所有节点均为顶层父节点。可以右键单击这些节点以查看可在其中添加的子节点的列表。这是将节点添加到模型树的方式。</p>\\n<p>当您单击某个子节点时，可以在设置窗口中查看其节点设置。您可以在此编辑节点设置。</p>\\n\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
