import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/software/vscode/guide/intellisense.html.vue"
const data = JSON.parse("{\"path\":\"/software/vscode/guide/intellisense.html\",\"title\":\"智能提示\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"智能提示\",\"icon\":\"creative\",\"category\":\"VS Code\",\"tag\":[\"VS Code\",\"软件\"],\"description\":\"使用 Ctrl + Space 触发智能提示组件。 智能提示组件智能提示组件 您可以查看可用的方法，参数提示，简短文档等。 跳转 选择一个符号然后输入 Alt + F12，您就可以使用上下文菜单了。 上下文菜单上下文菜单 跳转到定义 选择一个符号然后输入 F12，您也可以使用上下文菜单或 Ctrl + Click 跳转到定义跳转到定义 您可以使用 转到...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/software/vscode/guide/intellisense.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"智能提示\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"使用 Ctrl + Space 触发智能提示组件。 智能提示组件智能提示组件 您可以查看可用的方法，参数提示，简短文档等。 跳转 选择一个符号然后输入 Alt + F12，您就可以使用上下文菜单了。 上下文菜单上下文菜单 跳转到定义 选择一个符号然后输入 F12，您也可以使用上下文菜单或 Ctrl + Click 跳转到定义跳转到定义 您可以使用 转到...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"VS Code\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"软件\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"智能提示\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"跳转\",\"slug\":\"跳转\",\"link\":\"#跳转\",\"children\":[]},{\"level\":2,\"title\":\"跳转到定义\",\"slug\":\"跳转到定义\",\"link\":\"#跳转到定义\",\"children\":[]},{\"level\":2,\"title\":\"跳转到引用\",\"slug\":\"跳转到引用\",\"link\":\"#跳转到引用\",\"children\":[]},{\"level\":2,\"title\":\"查看所有引用\",\"slug\":\"查看所有引用\",\"link\":\"#查看所有引用\",\"children\":[]},{\"level\":2,\"title\":\"重命名符号\",\"slug\":\"重命名符号\",\"link\":\"#重命名符号\",\"children\":[]},{\"level\":2,\"title\":\"搜索和修改\",\"slug\":\"搜索和修改\",\"link\":\"#搜索和修改\",\"children\":[]},{\"level\":2,\"title\":\".eslintrc.json\",\"slug\":\"eslintrc-json\",\"link\":\"#eslintrc-json\",\"children\":[]},{\"level\":2,\"title\":\"package.json\",\"slug\":\"package-json\",\"link\":\"#package-json\",\"children\":[]},{\"level\":2,\"title\":\"Emmet 语法\",\"slug\":\"emmet-语法\",\"link\":\"#emmet-语法\",\"children\":[]}],\"readingTime\":{\"minutes\":1.73,\"words\":520},\"filePathRelative\":\"software/vscode/guide/intellisense.md\",\"excerpt\":\"<p>使用 <code>Ctrl + Space</code> 触发智能提示组件。</p>\\n<figure><figcaption>智能提示组件</figcaption></figure>\\n<p>您可以查看可用的方法，参数提示，简短文档等。</p>\\n<h2>跳转</h2>\\n<p>选择一个符号然后输入 <code>Alt + F12</code>，您就可以使用上下文菜单了。</p>\\n<figure><figcaption>上下文菜单</figcaption></figure>\\n<h2>跳转到定义</h2>\\n<p>选择一个符号然后输入 <code>F12</code>，您也可以使用上下文菜单或 <code>Ctrl + Click</code></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
