version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    groups:
      all:
        patterns:
          - '*'
    commit-message:
      prefix: 'fix(Dependabot)'