import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/design/articles/infomation-flow.html.vue"
const data = JSON.parse("{\"path\":\"/design/articles/infomation-flow.html\",\"title\":\"信息流介绍\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"信息流介绍\",\"icon\":\"note\",\"date\":\"2020-09-26T00:00:00.000Z\",\"category\":\"设计\",\"tag\":[\"UI\"],\"description\":\"今日头条的出现颠覆了传统新闻产品(如网易、新浪和搜狐新闻)。 传统新闻依靠着编辑人员的推荐，将新闻触达给用户，而今日头条则依靠着新闻算法，抛弃传统人工分发的思路，使分发效率数以万计的提升，其迅速崛起，成为头部新闻资讯产品。 今日头条作为新闻信息流的头部产品，里面的设计细节和设计逻辑值得我们思考和分析。 信息流样式 什么是信息流? 信息流由两部分组成，信...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/design/articles/infomation-flow.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"信息流介绍\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"今日头条的出现颠覆了传统新闻产品(如网易、新浪和搜狐新闻)。 传统新闻依靠着编辑人员的推荐，将新闻触达给用户，而今日头条则依靠着新闻算法，抛弃传统人工分发的思路，使分发效率数以万计的提升，其迅速崛起，成为头部新闻资讯产品。 今日头条作为新闻信息流的头部产品，里面的设计细节和设计逻辑值得我们思考和分析。 信息流样式 什么是信息流? 信息流由两部分组成，信...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"UI\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-09-26T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"信息流介绍\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-09-26T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"信息流样式\",\"slug\":\"信息流样式\",\"link\":\"#信息流样式\",\"children\":[{\"level\":3,\"title\":\"小结\",\"slug\":\"小结\",\"link\":\"#小结\",\"children\":[]}]},{\"level\":2,\"title\":\"信息流分发\",\"slug\":\"信息流分发\",\"link\":\"#信息流分发\",\"children\":[]},{\"level\":2,\"title\":\"搜索栏\",\"slug\":\"搜索栏\",\"link\":\"#搜索栏\",\"children\":[]},{\"level\":2,\"title\":\"短视频\",\"slug\":\"短视频\",\"link\":\"#短视频\",\"children\":[]},{\"level\":2,\"title\":\"小视频\",\"slug\":\"小视频\",\"link\":\"#小视频\",\"children\":[]},{\"level\":2,\"title\":\"短内容流\",\"slug\":\"短内容流\",\"link\":\"#短内容流\",\"children\":[]}],\"readingTime\":{\"minutes\":6.97,\"words\":2090},\"filePathRelative\":\"design/articles/infomation-flow.md\",\"localizedDate\":\"2020年9月26日\",\"excerpt\":\"<p>今日头条的出现颠覆了传统新闻产品(如网易、新浪和搜狐新闻)。</p>\\n<p>传统新闻依靠着编辑人员的推荐，将新闻触达给用户，而今日头条则依靠着新闻算法，抛弃传统人工分发的思路，使分发效率数以万计的提升，其迅速崛起，成为头部新闻资讯产品。</p>\\n<p>今日头条作为新闻信息流的头部产品，里面的设计细节和设计逻辑值得我们思考和分析。</p>\\n<h2>信息流样式</h2>\\n<p>什么是信息流? 信息流由两部分组成，信息流=信息+流。</p>\\n<p>信息指的是内容，这些内容可以是新闻、视频、图片等，所呈现的样式多为列表或卡片。</p>\\n<p>流指的是瀑布流，可以无限滑动浏览。</p>\\n<p>所以信息流就是可以无限滑动浏览内容信息。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
