import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/software/comsol/geometry/build.html.vue"
const data = JSON.parse("{\"path\":\"/software/comsol/geometry/build.html\",\"title\":\"几何构建\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"几何构建\",\"icon\":\"build\",\"date\":\"2020-05-29T00:00:00.000Z\",\"category\":\"软件\",\"tag\":[\"仿真\",\"COMSOL\"],\"description\":\"2D 几何 COMSOL Multiphysics® 软件提供了大量的几何操作、工具或功能来创建二维几何结构。软件中内置了可用于模拟常见形状的几何体，用于定义几何尺寸和位置的参数设置，以及可用于构建复杂几何结构的布尔运算、变换与分割几何操作。 您可以很轻松的添加圆和矩形对象，也可以使用参数曲线或多边形很轻松的创建您需要的形状。 使用并集和差集这两种布尔...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/software/comsol/geometry/build.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"几何构建\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"2D 几何 COMSOL Multiphysics® 软件提供了大量的几何操作、工具或功能来创建二维几何结构。软件中内置了可用于模拟常见形状的几何体，用于定义几何尺寸和位置的参数设置，以及可用于构建复杂几何结构的布尔运算、变换与分割几何操作。 您可以很轻松的添加圆和矩形对象，也可以使用参数曲线或多边形很轻松的创建您需要的形状。 使用并集和差集这两种布尔...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"仿真\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"COMSOL\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-05-29T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"几何构建\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-05-29T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"2D 几何\",\"slug\":\"_2d-几何\",\"link\":\"#_2d-几何\",\"children\":[]},{\"level\":2,\"title\":\"将二维图形扩展到三维\",\"slug\":\"将二维图形扩展到三维\",\"link\":\"#将二维图形扩展到三维\",\"children\":[]},{\"level\":2,\"title\":\"三维图像\",\"slug\":\"三维图像\",\"link\":\"#三维图像\",\"children\":[]},{\"level\":2,\"title\":\"基于三维结构创建二维模型\",\"slug\":\"基于三维结构创建二维模型\",\"link\":\"#基于三维结构创建二维模型\",\"children\":[]},{\"level\":2,\"title\":\"“形成联合体”和“形成装配”\",\"slug\":\"形成联合体-和-形成装配\",\"link\":\"#形成联合体-和-形成装配\",\"children\":[]}],\"readingTime\":{\"minutes\":5.15,\"words\":1546},\"filePathRelative\":\"software/comsol/geometry/build.md\",\"localizedDate\":\"2020年5月29日\",\"excerpt\":\"<h2>2D 几何</h2>\\n<p>COMSOL Multiphysics<sup>®</sup> 软件提供了大量的几何操作、工具或功能来创建二维几何结构。软件中内置了可用于模拟常见形状的几何体，用于定义几何尺寸和位置的参数设置，以及可用于构建复杂几何结构的布尔运算、变换与分割几何操作。</p>\\n<ul>\\n<li>您可以很轻松的添加圆和矩形对象，也可以使用参数曲线或多边形很轻松的创建您需要的形状。</li>\\n<li>使用并集和差集这两种布尔运算来创建如圆环形、葫芦的几何结构。</li>\\n<li>执行复制、阵列和镜像变换等操作来快速创建相同或相似的结合结构。</li>\\n</ul>\\n<h2>将二维图形扩展到三维</h2>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
