import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/linux/intro/history.html.vue"
const data = JSON.parse("{\"path\":\"/linux/intro/history.html\",\"title\":\"Linux 和 UNIX\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"time\",\"date\":\"2019-11-15T00:00:00.000Z\",\"category\":\"Linux\",\"tag\":[\"介绍\"],\"description\":\"Linux 和 UNIX UNIX 与 Linux 之间的关系是一个很有意思的话题。在目前主流的服务器端操作系统中，UNIX 诞生于 20 世纪 60 年代末，Windows 诞生于 20 世纪 80 年代中期，Linux 诞生于 20 世纪 90 年代初，可以说 UNIX 是操作系统中的\\\"老大哥\\\"，后来的 Windows 和 Linux 都参考了 U...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/linux/intro/history.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Linux 和 UNIX\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Linux 和 UNIX UNIX 与 Linux 之间的关系是一个很有意思的话题。在目前主流的服务器端操作系统中，UNIX 诞生于 20 世纪 60 年代末，Windows 诞生于 20 世纪 80 年代中期，Linux 诞生于 20 世纪 90 年代初，可以说 UNIX 是操作系统中的\\\"老大哥\\\"，后来的 Windows 和 Linux 都参考了 U...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"介绍\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-11-15T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Linux 和 UNIX\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2019-11-15T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"UNIX 的坎坷历史\",\"slug\":\"unix-的坎坷历史\",\"link\":\"#unix-的坎坷历史\",\"children\":[]},{\"level\":2,\"title\":\"Solaris 和 FreeBSD\",\"slug\":\"solaris-和-freebsd\",\"link\":\"#solaris-和-freebsd\",\"children\":[]},{\"level\":2,\"title\":\"Linux 的那些往事\",\"slug\":\"linux-的那些往事\",\"link\":\"#linux-的那些往事\",\"children\":[]},{\"level\":2,\"title\":\"UNIX 与 Linux 的关系\",\"slug\":\"unix-与-linux-的关系\",\"link\":\"#unix-与-linux-的关系\",\"children\":[]},{\"level\":2,\"title\":\"UNIX/Linux 系统结构\",\"slug\":\"unix-linux-系统结构\",\"link\":\"#unix-linux-系统结构\",\"children\":[]},{\"level\":2,\"title\":\"协议\",\"slug\":\"协议\",\"link\":\"#协议\",\"children\":[]}],\"readingTime\":{\"minutes\":12.46,\"words\":3738},\"filePathRelative\":\"linux/intro/history.md\",\"localizedDate\":\"2019年11月15日\",\"excerpt\":\"\\n<p>UNIX 与 Linux 之间的关系是一个很有意思的话题。在目前主流的服务器端操作系统中，UNIX 诞生于 20 世纪 60 年代末，Windows 诞生于 20 世纪 80 年代中期，Linux 诞生于 20 世纪 90 年代初，可以说 UNIX 是操作系统中的\\\"老大哥\\\"，后来的 Windows 和 Linux 都参考了 UNIX。</p>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">提示</p>\\n<p>现代的 Windows 系统已经朝着“图形界面”的方向发展了，和 UNIX 系统有了巨大的差异，从表面上甚至看不出两者的关联。</p>\\n</div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
