import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/linux/command/path.html.vue"
const data = JSON.parse("{\"path\":\"/linux/command/path.html\",\"title\":\"环境变量\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"shell\",\"date\":\"2019-11-20T00:00:00.000Z\",\"category\":\"Linux\",\"description\":\"环境变量 变量 变量是计算机系统用于保存可变值的数据类型，我们可以直接通过变量名称来提取到对应的变量值。在 Linux 系统中，环境变量是用来定义系统运行环境的一些参数，比如每个用户不同的家目录 (HOME)、邮件存放位置 (MAIL)等。 值得一提的是，Linux 系统中环境变量的名称一般都是大写的，这是一种约定俗成的规范。 我们可以使用 env 命...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/linux/command/path.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"环境变量\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"环境变量 变量 变量是计算机系统用于保存可变值的数据类型，我们可以直接通过变量名称来提取到对应的变量值。在 Linux 系统中，环境变量是用来定义系统运行环境的一些参数，比如每个用户不同的家目录 (HOME)、邮件存放位置 (MAIL)等。 值得一提的是，Linux 系统中环境变量的名称一般都是大写的，这是一种约定俗成的规范。 我们可以使用 env 命...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-11-20T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"环境变量\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2019-11-20T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"变量\",\"slug\":\"变量\",\"link\":\"#变量\",\"children\":[]},{\"level\":2,\"title\":\"path\",\"slug\":\"path\",\"link\":\"#path\",\"children\":[]}],\"readingTime\":{\"minutes\":4.85,\"words\":1454},\"filePathRelative\":\"linux/command/path.md\",\"localizedDate\":\"2019年11月20日\",\"excerpt\":\"\\n<h2>变量</h2>\\n<p>变量是计算机系统用于保存可变值的数据类型，我们可以直接通过变量名称来提取到对应的变量值。在 Linux 系统中，环境变量是用来定义系统运行环境的一些参数，比如每个用户不同的家目录 (HOME)、邮件存放位置 (MAIL)等。\\n值得一提的是，Linux 系统中环境变量的名称一般都是大写的，这是一种约定俗成的规范。</p>\\n<p>我们可以使用 env 命令来查看到 Linux 系统中所有的环境变量，执行命令如下:</p>\\n<div class=\\\"language-shell-session\\\" data-ext=\\\"shell-session\\\" data-title=\\\"shell-session\\\"><pre class=\\\"language-shell-session\\\"><code><span class=\\\"token command\\\"><span class=\\\"token info punctuation\\\"><span class=\\\"token user\\\">[root@localhost ~]</span></span><span class=\\\"token shell-symbol important\\\">#</span> <span class=\\\"token bash language-bash\\\"><span class=\\\"token function\\\">env</span></span></span>\\n<span class=\\\"token output\\\">ORBIT_SOCKETDIR=/tmp/orbit-root\\nHOSTNAME=livecd.centos\\nGIO_LAUNCHED_DESKTOP_FILE_PID=2065\\nTERM=xterm\\nSHELL=/bin/bash\\n......\\n</span></code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
