import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/software/comsol/mesh/index.html.vue"
const data = JSON.parse("{\"path\":\"/software/comsol/mesh/\",\"title\":\"网格\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"网格\",\"icon\":\"mesh\",\"date\":\"2020-06-02T00:00:00.000Z\",\"category\":\"软件\",\"tag\":[\"仿真\",\"COMSOL\"],\"description\":\"网格基础 内容 剖分方法 物理场控制 用户控制 剖分程度 从极粗化到极细化一共九个级别。 其他 可以进行定制。 基础 教程视频: 在 COMSOL Multiphysics® 中为几何模型构建网格 在 COMSOL Multiphysics® 中剖分网格 博客: 网格剖分原理介绍 如何检查 COMSOL Multiphysics® 中的网格 案例: 使...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/software/comsol/mesh/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"网格\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"网格基础 内容 剖分方法 物理场控制 用户控制 剖分程度 从极粗化到极细化一共九个级别。 其他 可以进行定制。 基础 教程视频: 在 COMSOL Multiphysics® 中为几何模型构建网格 在 COMSOL Multiphysics® 中剖分网格 博客: 网格剖分原理介绍 如何检查 COMSOL Multiphysics® 中的网格 案例: 使...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"仿真\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"COMSOL\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-06-02T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"网格\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-06-02T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"网格基础\",\"slug\":\"网格基础\",\"link\":\"#网格基础\",\"children\":[{\"level\":3,\"title\":\"内容\",\"slug\":\"内容\",\"link\":\"#内容\",\"children\":[]},{\"level\":3,\"title\":\"基础\",\"slug\":\"基础\",\"link\":\"#基础\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.88,\"words\":264},\"filePathRelative\":\"software/comsol/mesh/README.md\",\"localizedDate\":\"2020年6月2日\",\"excerpt\":\"<h2>网格基础</h2>\\n<ul>\\n<li><a href=\\\"/software/comsol/mesh/intro.html\\\" target=\\\"_blank\\\">网格划分和细化介绍</a></li>\\n</ul>\\n<h3>内容</h3>\\n<h4>剖分方法</h4>\\n<ul>\\n<li>物理场控制</li>\\n<li>用户控制</li>\\n</ul>\\n<h4>剖分程度</h4>\\n<p>从极粗化到极细化一共九个级别。</p>\\n<h4>其他</h4>\\n<p>可以进行定制。</p>\\n<h3>基础</h3>\\n<p>教程视频:</p>\\n<ul>\\n<li>\\n<p><a href=\\\"https://cn.comsol.com/video/building-the-mesh-for-a-model-geometry-in-comsol-multiphysics\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">在 COMSOL Multiphysics<sup>®</sup> 中为几何模型构建网格</a></p>\\n</li>\\n<li>\\n<p><a href=\\\"https://cn.comsol.com/video/meshing-in-comsol-multiphysics-tutorial-cn\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">在 COMSOL Multiphysics<sup>®</sup> 中剖分网格</a></p>\\n</li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
