import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/design/navigation/navbar.html.vue"
const data = JSON.parse("{\"path\":\"/design/navigation/navbar.html\",\"title\":\"导航栏设计\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"导航栏设计\",\"icon\":\"footer\",\"date\":\"2020-09-15T00:00:00.000Z\",\"category\":\"设计\",\"tag\":[\"导航\",\"Navbar\"],\"description\":\"其实网页或者 App 中的导航(Navigation)这个概念远不止我们熟悉的导航栏，而是一个更加广的交互概念: 引导用户和产品进行有效的交互，实现用户的目标。 导航栏究竟在哪里 导航栏 Navigation Bar，也简称为 Navbar。一定会有不少刚入门的 UI 新人，在诸多的 Bar 控件中，难以区分它所指代的区域。 在 iOS 上，导航栏是指...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/design/navigation/navbar.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"导航栏设计\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"其实网页或者 App 中的导航(Navigation)这个概念远不止我们熟悉的导航栏，而是一个更加广的交互概念: 引导用户和产品进行有效的交互，实现用户的目标。 导航栏究竟在哪里 导航栏 Navigation Bar，也简称为 Navbar。一定会有不少刚入门的 UI 新人，在诸多的 Bar 控件中，难以区分它所指代的区域。 在 iOS 上，导航栏是指...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"导航\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Navbar\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-09-15T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"导航栏设计\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-09-15T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"导航栏究竟在哪里\",\"slug\":\"导航栏究竟在哪里\",\"link\":\"#导航栏究竟在哪里\",\"children\":[]},{\"level\":2,\"title\":\"规范里告诉我们该怎么做 vs 实际项目我们该怎么做\",\"slug\":\"规范里告诉我们该怎么做-vs-实际项目我们该怎么做\",\"link\":\"#规范里告诉我们该怎么做-vs-实际项目我们该怎么做\",\"children\":[{\"level\":3,\"title\":\"导航栏标题\",\"slug\":\"导航栏标题\",\"link\":\"#导航栏标题\",\"children\":[]},{\"level\":3,\"title\":\"导航按钮及内容控件按钮\",\"slug\":\"导航按钮及内容控件按钮\",\"link\":\"#导航按钮及内容控件按钮\",\"children\":[]},{\"level\":3,\"title\":\"分割线\",\"slug\":\"分割线\",\"link\":\"#分割线\",\"children\":[]},{\"level\":3,\"title\":\"其他控件\",\"slug\":\"其他控件\",\"link\":\"#其他控件\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":7.53,\"words\":2259},\"filePathRelative\":\"design/navigation/navbar.md\",\"localizedDate\":\"2020年9月15日\",\"excerpt\":\"<p>其实网页或者 App 中的导航(Navigation)这个概念远不止我们熟悉的导航栏，而是一个更加广的交互概念: 引导用户和产品进行有效的交互，实现用户的目标。</p>\\n<h2>导航栏究竟在哪里</h2>\\n<p>导航栏 Navigation Bar，也简称为 Navbar。一定会有不少刚入门的 UI 新人，在诸多的 Bar 控件中，难以区分它所指代的区域。</p>\\n<p>在 iOS 上，导航栏是指显示在应用程序顶部，位于状态栏下方的容器区域，层级应高于当前页面内容。</p>\\n<p>在安卓上，Google 公司在 Material Design 中也赋予了它同样的定义，但是却给了它另一个名称，顶部应用栏(Top App Bar)。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
