import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/design/icon/line.html.vue"
const data = JSON.parse("{\"path\":\"/design/icon/line.html\",\"title\":\"线性图标设计\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"线性图标设计\",\"icon\":\"exercise\",\"date\":\"2020-09-13T00:00:00.000Z\",\"category\":\"设计\",\"tag\":[\"Icon\"],\"description\":\"线性图标是所有图标中最基础的设计形式，也是最简单的入门。在我们后续设计其它的风格图标前，首先要通过练习线性图标来打下坚实的基础。\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/design/icon/line.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"线性图标设计\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"线性图标是所有图标中最基础的设计形式，也是最简单的入门。在我们后续设计其它的风格图标前，首先要通过练习线性图标来打下坚实的基础。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Icon\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-09-13T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"线性图标设计\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-09-13T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"设计注意事项\",\"slug\":\"设计注意事项\",\"link\":\"#设计注意事项\",\"children\":[]},{\"level\":2,\"title\":\"设计演示\",\"slug\":\"设计演示\",\"link\":\"#设计演示\",\"children\":[{\"level\":3,\"title\":\"搜索图标\",\"slug\":\"搜索图标\",\"link\":\"#搜索图标\",\"children\":[]},{\"level\":3,\"title\":\"聊天图标\",\"slug\":\"聊天图标\",\"link\":\"#聊天图标\",\"children\":[]},{\"level\":3,\"title\":\"查看图标\",\"slug\":\"查看图标\",\"link\":\"#查看图标\",\"children\":[]},{\"level\":3,\"title\":\"心形图标\",\"slug\":\"心形图标\",\"link\":\"#心形图标\",\"children\":[]},{\"level\":3,\"title\":\"卡券图标\",\"slug\":\"卡券图标\",\"link\":\"#卡券图标\",\"children\":[]},{\"level\":3,\"title\":\"房屋图标\",\"slug\":\"房屋图标\",\"link\":\"#房屋图标\",\"children\":[]},{\"level\":3,\"title\":\"齿轮图标\",\"slug\":\"齿轮图标\",\"link\":\"#齿轮图标\",\"children\":[]},{\"level\":3,\"title\":\"文件图标\",\"slug\":\"文件图标\",\"link\":\"#文件图标\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[{\"level\":3,\"title\":\"栅格的使用\",\"slug\":\"栅格的使用\",\"link\":\"#栅格的使用\",\"children\":[]},{\"level\":3,\"title\":\"图形的调整\",\"slug\":\"图形的调整\",\"link\":\"#图形的调整\",\"children\":[]},{\"level\":3,\"title\":\"多种操作方式\",\"slug\":\"多种操作方式\",\"link\":\"#多种操作方式\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.93,\"words\":2979},\"filePathRelative\":\"design/icon/line.md\",\"localizedDate\":\"2020年9月13日\",\"excerpt\":\"<p>线性图标是所有图标中最基础的设计形式，也是最简单的入门。在我们后续设计其它的风格图标前，首先要通过练习线性图标来打下坚实的基础。</p>\\n\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
