import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/linux/bash/archives/command.html.vue"
const data = JSON.parse("{\"path\":\"/linux/bash/archives/command.html\",\"title\":\"Shell 的命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"Shell 的命令 命令的类别 Bash 可以使用的命令分成四类。 可执行程序 Shell 提供的命令 Shell 函数 前三类命令的别名 type, whatis type 命令可以显示命令类型。 下面是几个例子。 whatis 命令显示指定命令的描述。 apropos apropos 命令返回符合搜索条件的命令列表。 alias, unalias ...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/linux/bash/archives/command.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Shell 的命令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Shell 的命令 命令的类别 Bash 可以使用的命令分成四类。 可执行程序 Shell 提供的命令 Shell 函数 前三类命令的别名 type, whatis type 命令可以显示命令类型。 下面是几个例子。 whatis 命令显示指定命令的描述。 apropos apropos 命令返回符合搜索条件的命令列表。 alias, unalias ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Shell 的命令\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"命令的类别\",\"slug\":\"命令的类别\",\"link\":\"#命令的类别\",\"children\":[]},{\"level\":2,\"title\":\"type, whatis\",\"slug\":\"type-whatis\",\"link\":\"#type-whatis\",\"children\":[]},{\"level\":2,\"title\":\"apropos\",\"slug\":\"apropos\",\"link\":\"#apropos\",\"children\":[]},{\"level\":2,\"title\":\"alias, unalias\",\"slug\":\"alias-unalias\",\"link\":\"#alias-unalias\",\"children\":[]},{\"level\":2,\"title\":\"which\",\"slug\":\"which\",\"link\":\"#which\",\"children\":[]},{\"level\":2,\"title\":\"help，man\",\"slug\":\"help-man\",\"link\":\"#help-man\",\"children\":[]},{\"level\":2,\"title\":\"script\",\"slug\":\"script\",\"link\":\"#script\",\"children\":[]},{\"level\":2,\"title\":\"export\",\"slug\":\"export\",\"link\":\"#export\",\"children\":[]},{\"level\":2,\"title\":\"命令的连续执行\",\"slug\":\"命令的连续执行\",\"link\":\"#命令的连续执行\",\"children\":[]}],\"readingTime\":{\"minutes\":5.27,\"words\":1581},\"filePathRelative\":\"linux/bash/archives/command.md\",\"excerpt\":\"\\n<h2>命令的类别</h2>\\n<p>Bash 可以使用的命令分成四类。</p>\\n<ul>\\n<li>可执行程序</li>\\n<li>Shell 提供的命令</li>\\n<li>Shell 函数</li>\\n<li>前三类命令的别名</li>\\n</ul>\\n<h2>type, whatis</h2>\\n<p><code>type</code> 命令可以显示命令类型。</p>\\n<div class=\\\"language-bash\\\" data-ext=\\\"sh\\\" data-title=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code><span class=\\\"token builtin class-name\\\">type</span> <span class=\\\"token builtin class-name\\\">command</span>\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
