import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/linux/bash/archives/text.html.vue"
const data = JSON.parse("{\"path\":\"/linux/bash/archives/text.html\",\"title\":\"文本处理\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"文本处理 cat cat 可以文件的内容，显示在标准输出。 它也可以同时输出多个文件内容。 它与重定向结合，就可以合并多个文件。 如果调用 cat 命令时没有任何参数，它将读取标准输入，然后显示到标准输出。按下 Ctrl + d，将会结束 cat 读取标准输入。利用这一点，可以将键盘输入写入指定文件，按下 Ctrl + d 结束输入。 它的参数如下。 ...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/linux/bash/archives/text.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"文本处理\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"文本处理 cat cat 可以文件的内容，显示在标准输出。 它也可以同时输出多个文件内容。 它与重定向结合，就可以合并多个文件。 如果调用 cat 命令时没有任何参数，它将读取标准输入，然后显示到标准输出。按下 Ctrl + d，将会结束 cat 读取标准输入。利用这一点，可以将键盘输入写入指定文件，按下 Ctrl + d 结束输入。 它的参数如下。 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"文本处理\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"cat\",\"slug\":\"cat\",\"link\":\"#cat\",\"children\":[]},{\"level\":2,\"title\":\"nl\",\"slug\":\"nl\",\"link\":\"#nl\",\"children\":[]},{\"level\":2,\"title\":\"sort\",\"slug\":\"sort\",\"link\":\"#sort\",\"children\":[]},{\"level\":2,\"title\":\"uniq\",\"slug\":\"uniq\",\"link\":\"#uniq\",\"children\":[]},{\"level\":2,\"title\":\"cut\",\"slug\":\"cut\",\"link\":\"#cut\",\"children\":[]},{\"level\":2,\"title\":\"paste\",\"slug\":\"paste\",\"link\":\"#paste\",\"children\":[]},{\"level\":2,\"title\":\"wc\",\"slug\":\"wc\",\"link\":\"#wc\",\"children\":[]},{\"level\":2,\"title\":\"head\",\"slug\":\"head\",\"link\":\"#head\",\"children\":[]},{\"level\":2,\"title\":\"tail\",\"slug\":\"tail\",\"link\":\"#tail\",\"children\":[]},{\"level\":2,\"title\":\"grep\",\"slug\":\"grep\",\"link\":\"#grep\",\"children\":[]},{\"level\":2,\"title\":\"sed\",\"slug\":\"sed\",\"link\":\"#sed\",\"children\":[]}],\"readingTime\":{\"minutes\":5.86,\"words\":1759},\"filePathRelative\":\"linux/bash/archives/text.md\",\"excerpt\":\"\\n<h2>cat</h2>\\n<p><code>cat</code> 可以文件的内容，显示在标准输出。</p>\\n<div class=\\\"language-bash\\\" data-ext=\\\"sh\\\" data-title=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code>$ <span class=\\\"token function\\\">cat</span> text1\\n<span class=\\\"token number\\\">1</span> apple\\n<span class=\\\"token number\\\">2</span> pear\\n<span class=\\\"token number\\\">3</span> banana\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
