import comp from "D:/Administrator/Desktop/viptv-private/docs/.vuepress/.temp/pages/software/index.html.vue"
const data = JSON.parse("{\"path\":\"/software/\",\"title\":\"软件教程\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"软件教程\",\"icon\":\"software\",\"star\":9,\"sticky\":9,\"description\":\"代码编辑器 团队协作 开发项目的代码版本管理以及多人协作使用 Git 软件 浏览器 在开发中，调试网页推荐使用 Chrome。 后端 Http Server 网站已经停止使用 Apache Lounge 编译的 httpd Apache。目前迁移到更加轻量，并发性能更好的 Nginx 上。 抓包与 API 调试 工具软件 手机 APP soloLear...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://viptv.work/software/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"VIPTV - 云视听\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"软件教程\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"代码编辑器 团队协作 开发项目的代码版本管理以及多人协作使用 Git 软件 浏览器 在开发中，调试网页推荐使用 Chrome。 后端 Http Server 网站已经停止使用 Apache Lounge 编译的 httpd Apache。目前迁移到更加轻量，并发性能更好的 Nginx 上。 抓包与 API 调试 工具软件 手机 APP soloLear...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"VIPTV - 云视听\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"软件教程\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"VIPTV - 云视听\\\",\\\"url\\\":\\\"/about\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"代码编辑器\",\"slug\":\"代码编辑器\",\"link\":\"#代码编辑器\",\"children\":[]},{\"level\":2,\"title\":\"团队协作\",\"slug\":\"团队协作\",\"link\":\"#团队协作\",\"children\":[]},{\"level\":2,\"title\":\"浏览器\",\"slug\":\"浏览器\",\"link\":\"#浏览器\",\"children\":[]},{\"level\":2,\"title\":\"后端\",\"slug\":\"后端\",\"link\":\"#后端\",\"children\":[{\"level\":3,\"title\":\"Http Server\",\"slug\":\"http-server\",\"link\":\"#http-server\",\"children\":[]},{\"level\":3,\"title\":\"抓包与 API 调试\",\"slug\":\"抓包与-api-调试\",\"link\":\"#抓包与-api-调试\",\"children\":[]}]},{\"level\":2,\"title\":\"工具软件\",\"slug\":\"工具软件\",\"link\":\"#工具软件\",\"children\":[]},{\"level\":2,\"title\":\"手机 APP\",\"slug\":\"手机-app\",\"link\":\"#手机-app\",\"children\":[{\"level\":3,\"title\":\"soloLearn\",\"slug\":\"sololearn\",\"link\":\"#sololearn\",\"children\":[]}]},{\"level\":2,\"title\":\"Adobe 软件\",\"slug\":\"adobe-软件\",\"link\":\"#adobe-软件\",\"children\":[]}],\"readingTime\":{\"minutes\":0.82,\"words\":245},\"filePathRelative\":\"software/README.md\",\"excerpt\":\"<h2>代码编辑器</h2>\\n<ul>\\n<li><a href=\\\"/software/editor.html\\\" target=\\\"_blank\\\">编辑器介绍</a></li>\\n</ul>\\n<h2>团队协作</h2>\\n<p>开发项目的代码版本管理以及多人协作使用 Git 软件</p>\\n<ul>\\n<li>\\n<p><a href=\\\"/software/git/\\\" target=\\\"_blank\\\">Git 教程</a></p>\\n</li>\\n<li>\\n<p><a href=\\\"/code/github/\\\" target=\\\"_blank\\\">GitHub 介绍</a></p>\\n</li>\\n</ul>\\n<h2>浏览器</h2>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
