import { sidebar } from "vuepress-theme-hope";
import archives from "./archives.js";
export const zhSidebar = sidebar({
  "/vod/": [
    "",
    {
      text: "电影",
      icon: "lock-open",
      prefix: "movie/",
      children: "structure",
      collapsible: true,
    },
    {
      text: "剧集",
      icon: "lock-open",
      prefix: "tvb/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "动漫",
      icon: "lock-open",
      prefix: "dongman/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "综艺",
      icon: "lock-open",
      prefix: "zongyi/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "体育",
      icon: "lock-open",
      prefix: "sport/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "短剧",
      icon: "lock-open",
      prefix: "duanju/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "视频",
      icon: "lock-open",
      prefix: "video/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "伦理",
      icon: "lock",
      prefix: "lunli/",
      collapsible: true,
      children: "structure",
    },
  ],
  "/iptv/": [
    "",
    {
      text: "央视",
      prefix: "cctv/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
    {
      text: "卫视",
      prefix: "weishi/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
    {
      text: "地方",
      prefix: "difang/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
    {
      text: "港台",
      prefix: "gangtai/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
    {
      text: "境外",
      prefix: "jingwai/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
  ],
  "/music/": [
    "",
    {
      text: "歌曲",
      prefix: "gequ/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
    {
      text: "舞曲",
      prefix: "wuqu/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
    {
      text: "音乐",
      prefix: "music/",
      collapsible: true,
      icon: "lock-open",
      children: "structure",
    },
  ],
  "/archives/": archives,
  "/": [
    "" /* / */,
    "contact" /* /contact.html */,
    "about/" /* /about.html */,
  ],
});
