name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"
env:
  TZ: Asia/Shanghai   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GetTime
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: update bing wallpaper
        run: pnpm run tsup 

      - name: Build Docs
        run: pnpm run build   
        
      - name: Deploy to viptv-work/viptv
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: viptv-work/viptv
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: viptv.work

      - name: Deploy to hefung/docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: hefung/docs
          publish_dir: ./dist
          publish_branch: main  