name: Deploy docs
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to viptv-work/viptv
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: viptv-work/viptv
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: viptv.work

      - name: Deploy to hefung/docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: hefung/docs
          publish_dir: ./dist
          publish_branch: main

