name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run tsup && pnpm run build
        
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: viptv-work/viptv
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: viptv.work

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: hefung/docs
          publish_dir: ./dist
          publish_branch: main