name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"
jobs:
  deploy-github-pages:
    name: Deploy docs to GitHub pages
    if: github.repository == 'viptv-work/viptv-private'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true
          version: latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm 
      
      - name: Install deps
        run: pnpm install --frozen-lockfile    
      
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build
      
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: viptv-work/viptv
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ secrets.PUBLISH_DOCS }}
          single-commit: true