name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
<<<<<<< HEAD

      - name: 设置 Node.js
=======
          
      - name: Setup Node.js
>>>>>>> 9ebb3cfcf2725e110d1dbae7f25e96592c1477c6
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
<<<<<<< HEAD
      - name: 安装依赖
=======
      - name: Install deps
>>>>>>> 9ebb3cfcf2725e110d1dbae7f25e96592c1477c6
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
<<<<<<< HEAD
          > dist/.nojekyll
=======
          > /dist/.nojekyll
>>>>>>> 9ebb3cfcf2725e110d1dbae7f25e96592c1477c6
        
      - name: 部署文档
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_DOCS }}
          external_repository: viptv-work/viptv
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: viptv.work
